site_name: Elizabeth Goltz
site_description: Work samples, projects, and experiments
site_url: https://egoltz.github.io
repo_url: https://github.com/egoltz/egoltz.github.io
theme:
  name: material

nav:
  - Work: 
      - Overview: index.md
      - Projects: 
          - Overview: work/projects/index.md
          - Optimizing Nonprofit Clinic Locations: work/projects/clinic-locations.md
 #         - Sales Forecasting Dashboard: work/projects/sales-forecasting.md
#          - Chatbot Trends Analysis: work/projects/chatbot-trends.md
      - Data Engineering:
          - Overview: work/data-engineering/index.md
          - Database Update - Stored Procedure: work/data-engineering/stored-procedure.md
      - Financial Analysis: 
          - Overview: work/financial-analysis/index.md
#          - Toliza Art Museum Case Study: work/financial-analysis/toliza-art.md
          - Bridgestone Behavioral Health Case Study: work/financial-analysis/bridgestone.md
          - Ontario Police Case Study: work/financial-analysis/ontario-police.md
      - Visualization:
          - Overview: work/visualization/index.md
          - Optimal Moon-Viewing Calendar: work/visualization/moon-viewing.md
          - Image Color Analysis: work/visualization/color-analysis.md
  - About: about.md
  - CV: cv.md


