site_name: Elizabeth Goltz
site_description: Work samples, projects, and experiments
site_url: https://egoltz.github.io
repo_url: https://github.com/egoltz/egoltz.github.io
theme:
  name: material

nav:
  - Home: index.md
  - Projects & Work:
      - Overview: work/index.md
      - Systems & Data Engineering:
          - Overview: work/data-engineering/index.md
          - Database Update - Stored Procedure: work/data-engineering/stored-procedure.md
      - Financial Analysis: 
          - Overview: work/financial-analysis/index.md
          - Toliza Art Museum Case Study: work/financial-analysis/toliza-art.md
          - Ontario Police Case Study: work/financial-analysis/ontario-police.md
  - About: about.md
  - CV: cv.md


